- name: Publish
	uses: netlify/actions/cli@master
	with:
	  args: deploy --prod --dir=dist --message="Deploy from ${{ github.event.head_commit.message }}"
	env:
	  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
	  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}